#ifndef BOX_ERROR_H
#define BOX_ERROR_H

typedef enum {
  BOX_STATUS_OK,

  ERROR_BOX_RELATIONSHIP_ADDING_ENTITIES_WITH_DIFFERENT_RELATIONSHIP_TYPE,
  ERROR_BOX_RELATIONSHIP_ADDING_MORE_THAN_ONE,

  ERROR_BOX_ENTITY_UNKNOWN_RELATIONSHIP,

  ERROR_BOX_DATA_INVALID_DATA_TYPE,
  ERROR_BOX_DATA_NULL_DATA,
  ERROR_BOX_DATA_ASSIGNING_STRING,
  ERROR_BOX_DATA_ADDING_STRING,
  ERROR_BOX_DATA_SUBTRACTING_STRING,
  ERROR_BOX_DATA_LOGICAL_OPERATION_STRING,
  ERROR_BOX_DATA_LOGICAL_OPERATION_FLOAT,
  ERROR_BOX_DATA_MULTIPLYING_STRING,
  ERROR_BOX_DATA_INCREMENTING_STRING,
  ERROR_BOX_DATA_DECREMENTING_STRING,
  ERROR_BOX_DATA_DIVIDING_STRING,
  ERROR_BOX_DATA_DIVIDING_ZERO,
  ERROR_BOX_DATA_INVALID_MODULUS,
  ERROR_BOX_DATA_MODULUS_ZERO,

  ERROR_BOX_ARRAY_OUT_OF_BOUNDS,
  ERROR_BOX_ARRAY_ADDING_NULL_DATA,

  ERROR_BOX_DATA_MEMBER_INVALID_GROUP,
  ERROR_BOX_DATA_MEMBER_NULL_REFERENCE,
  ERROR_BOX_DATA_MEMBER_ARRAY_AS_DATA,
  ERROR_BOX_DATA_MEMBER_DATA_AS_ARRAY,

  ERROR_BOX_MEMBER_COLLECTION_DUPLICATE_KEY,
  ERROR_BOX_MEMBER_COLLECTION_INVALID_DATA_MEMBER,
  ERROR_BOX_MEMBER_COLLECTION_INVALID_MEMBER,

  ERROR_BOX_VIRTUAL_MEMORY_UNKNOWN_CHUNK,
  ERROR_BOX_VIRTUAL_MEMORY_ZERO_CAPACITY,
  ERROR_BOX_VIRTUAL_MEMORY_UNKNOWN_FAULT
} box_status;

class box_error {
public:
  box_error(box_status status, const char *func);
  bool operator == (box_error &another_error);
  void print();
  box_status get_status();
  const char *get_status_str();
protected:
  box_status status;
  const char *func;
};

#endif // BOX_ERROR_H
